<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<div style="width:750px;padding:25px;margin:0 auto;">
		<div style="margin:0 auto;">
			<img src="<?=base_url('images/lobos-logo-small.png')?>"/>
		</div>
		<h1 style="text-align:center">LIMITED POWER OF ATTORNEY</h1>
		<p style="text-align:center">STATE OF Utah, COUNTY OF Utah. Be it acknowledged that <?=$driver['f_name']?> <?=$driver['l_name']?> (Individual) <?=$driver['ssn']?> (Social security #) (Hereafter, the "Principal") does hereby designate and appoint:</p>
		<p style="text-align:center">Arrowhead Dispatch Services, LLC</p>
		<p style="text-align:center">1922 W 200 N, Lindon, UT 84042</p>
		<p style="text-align:center">(Hereafter, the "Appointed")</p>
		<p style="text-align:center">and employees or authorized agents designated by Direct Lease, and owners or managing</p>
		<p style="text-align:center"> members to act for an on behalf of the above named for the following special purposes:</p>
		<p>-Entering into equipment rental and lease contracts as both a lessee and a lessor potentially obligating the principle to make rental and / or lease payments and other obligations.</p>
		<p>-Create an entity or entities and make required updates for an entity or entities that shall serve as the principle's owner operator company and / or motor carrier company and to sign on behalf of the principle all paperwork necessary to complete this task.</p>
		<p>-Generate and sign government and tax documents such as the W-9 form, 10-99, and others and send them to the principle's businesses' customers.</p>
		<p>-Enter into and bind by signature agreements with shippers, receivers, brokers, and other customers to haul freight.</p>
		<p>-Resolving disputes and collecting money for work done by the principal and / or the principal's businesses.</p>
		<p>-Create and access bank accounts and sign all corresponding paperwork on behalf of the principle for the purpose of business
		transactions for the principle's owner operator and / or motor carrier businesses.</p>
		<p>-Make payments to vendors from principal's business bank accounts on behalf of principals businesses.</p>
		<p>-Manage and sign for the principle's businesses bank accounts</p>
		<p>-Apply for motor carrier authority and make necessary changes, updates, and filings on behalf of the principle's motor carrier and / or owner operator business including all federal and state documents including but not limited to the OP-1 and the MCS-150. This includes both signing paper and electronic documents that potentially bind the principal and / or his companies to government-mandated responsibilities such as safety requirements and others.</p>
		<p>-Apply for and make necessary changes, updates, and filings for all necessary permissions and permits in states and countries that the principal's owner operator business(es) and / or motor carrier business(es) does or will operate.</p>
		<p>-Enter into and bind by signature agreements to sell receivables to companies such as factoring companies.</p>
		<p>-Enter into and bind insurance agreements and policies with insurance companies on behalf of principle and it's companies and make updates to the policies, file claims associated with those policies, represent the principle and the principle's businesses on the phone and in disputes and in court with the insurance vendors, cancel the policies, pay for the policies, collect money from the policies paid to the principal and / or the principal's business for claims or returned premium or other money.</p>
		<p>-Sign court documents and represent the principle and the principle's businesses in court.</p>
		<p>-Hire employees and contractors to work for the principal and /or the principal's businesses and bind contracts by signature.</p>
		<p>-Enter into agreements and bind by signature contracts to lease principal and / or principal's businesses to a motor carrier and / or lease other owner operators and / or motor carriers to the principle's motor carrier business.</p>
		<p>-Enter into other agreements and bind by signature contracts relevant to the operation of the principle's businesses.</p>
		<p>-Enter into agreements and bind by signature contracts with safety management companies, cooperatives, dispatch service companies, trucking associations, load board and posting sites, and other service providers.</p>
		<p>This limited Power of Attorney is restricted and limited to the matters specifically set forth herein and for the term beginning ___________ 20_____and continuing until cancelled.</p>
		<p>SIGNATURE ______________________________________________ TITLE ______________________________________ Member</p>
		<p>LIMITED AGENCY AGREEMENT</p>
		<p>This Limited Agency Agreement (hereinafter "Agreement") is entered into this ____ day of __________, 20____, by and between ____________________________________ ("Driver") and Arrowhead Dispatch Services, LLC (hereinafter "Limited Agent" or "LA"), located at 1922 W 200 N Lindon, UT 84042.</p>
		<p>RECITALS:</p>
		<ol type="A">
			<li>LA is a bona fide agent as defined by 49 C.F.R. 371.2(b) that is part of Carrier's normal organization and that performs duties for Carrier under Carrier's directions pursuant to the terms set forth herein providing for a continuing relationship between LA and Carrier and precluding the exercise of discretion on the party of LA in allocating traffic between Carrier and others;</li>
			<li>Carrier is any interstate or intrastate motor carrier, of which Driver has ownership interest and authority to enter into this agreement on behalf of the Carrier, operating pursuant to authority granted to it to do so by the FMCSA and the U.S. Dept. of Transportation ("DOT") and/or pursuant to other permits and/or licenses to operate as an intrastate motor carrier granted to Carrier by one or more state regulatory agencies;</li>
			<li>LA and Carrier desire that LA be granted limited agency to perform services on behalf of Carrier to include booking freight for Carrier as Carrier's agent and managing additional day-to-day operational tasks for Carrier as set forth herein-below.</li>
		</ol>
		<p>AGREEMENT</p>
		<p>NOW THEREFORE, in consideration of the mutual promises and covenants contained herein, Carrier and LA hereby agree as follows:</pL>
		<ol type="1">
			<li>Duties of LA.
				<ol type="A">
					<li>LA understands that it will provide Carrier the following services under this Agreement: (1) arrange freight for Carrier as Carrier's limited agent; (2) assist Carrier in managing its owneroperator fleet as set forth herein.</li>
					<li>
						LA will find loads or freight and arrange to have such loads transported by Carrier. In doing so, LA will have to provide the name, address, and telephone number of the shipper(s) and consignee(s) of such goods, all necessary billing instructions, special billing numbers, a description of the goods to be hauled, any special loading or unloading instructions, information as to when and where the goods should be loaded and unloaded, the amount that the shipper(s), consignee(s) and/or thirdparty(ies) (hereinafter collectively referred to as "Customer") has agreed to pay for arranging the transportation of the goods, and any other information pertinent to arranging transportation of the goods. LA will not use any paperwork with Customer(s) that show an address other than Carrier's address.
						<p>Carrier hereby authorizes LA to sign the Rate Confirmation for each load tendered. After booking the load for Carrier, LA will send all documents related to booking the load to Carrier's accounting personnel for billing and collection (the "Freight Documents"). Once LA transfers the Freight Documents to Carrier, Carrier assumes responsibility for the custody and maintenance of the Freight Documents. Carrier designates United Motor Carrier Cooperative LCA as accounting personnel.</p>
					</li>
					<li>In arranging freight for Carrier, LA agrees to cover the following expenses: approved tolls, lumpers, oversize permits, gate fees and any other agreed upon expenses.</li>
					<li>Carrier agrees to cover all other expenses, including but not limited to: fuel, equipment leasing, insurance, repairs, load locks, straps, propane/tanks, lights, tires, jumper cables, fluids (oil, washer  fluid, radiator fluid, etc.), wipers, scales, tickets (violations), tire chains, phones, GPS units, maps, log books, food, and all other expenses.</li>
					<li>LA may also, at Carrier's discretion and direction, assist Carrier in managing Carrier's owneroperator fleet and contracts. In so doing, Carrier grants LA authority to work with third-party transportation vendors to find and present available owner-operators that can lease equipment and driver(s) onto Carrier. Carrier hereby authorizes LA to sign Carrier's Carrier/Owner-Operator Agreement on behalf of Carrier to effectuate the contractual relationship between Carrier and its owner-operator. Carrier is not obligated to take on owner-operators or enter into any lease agreement with any owner-operator found or presented to Carrier by LA. Carrier recognizes and agrees that it is able to access and review LA's work in managing Carrier's owner-operator fleet and contracts in real time and is obligated to address any issues with LA's management of the carrier fleet within forty-eight (48) hours of the information being posted. Any action taken by LA contrary to this provision is an Event of Default as defined in paragraph 13 below.</li>
					<li>During the term of this agreement, LA shall arrange freight for Carrier.</li>
					<li>LA will be required to provide its own copy the software necessary to fulfill its duties set forth herein. It is LA's responsibility to properly setup its own computer, load all software, and obtain a DSL line or cable modem, and to work with his own telephone and internet providers.</li>
					<li>LA is an independent contractor and as such is responsible for all payrolls for its employees and itself, including all payroll taxes. In the event any federal or state agency claims Carrier is responsible for any expenses of LA, LA will indemnify and hold harmless Carrier for all expenses, including court costs, attorney fees, and accountant fees, to defend such claims against Carrier.</li>
					<li>Any person who performs work for the LA in connection with LA's duties set forth in section 1(A) through 1(G), above, shall be the statutory employee of the LA. The LA shall not have any person who is not the statutory employee of the LA perform work in connection with or related to the terms of this Agreement.</li>
				</ol>
			</li>
			<li>Commitment of Driver
				<ol type="A">
					<li>Driver commits to stay in the truck and drive for the term of the contract according to the schedule agreed upon by both the Driver and LA. Such schedule will be communicated in written form between both parties. In the event that the driver desires to exit the truck and discontinue to drive, fourteen (14) days written notice must be provided from Driver to LA. In the event that the Driver exits or discontinues to drive without 14 days notice, Driver is subject to Early Termination Fees as referenced in section 9.</li>
				</ol>
			</li>
			<li>Payment. In consideration for LA's booking its freight, Carrier shall compensate LA in a weekly settlement according to the Payment Schedule attached hereto as Schedule A (hereinafter the "Payment Schedule").</li>
			<li>Manner of Payment. Once a load is booked for the Carrier, LA will send all information related to booking that load to Carrier's accounting department or third-party accounting service provider, at the sole discretion and direction of the Carrier, for billing and collection of the same.</li>
			<li>Routing of Payment. It is understood and agreed that should the Customer pay the amount of the freight contract or Freight Charges to LA rather than Carrier despite instructions to the contrary from LA and billing by Carrier and/or Carrier's billing agent, that LA shall endorse Customer's check, money order, draft, or other means of payment over to Carrier and shall immediately forward the same to Carrier. Upon receipt of such endorsed payment, Carrier shall pay the amount owed to LA (if not yet advanced) under the Payment Schedule. It will be an Event of Default (see paragraph. 13) under this Agreement should LA deposit or otherwise negotiate any check from a Customer into LA's account or an account of any other person or entity, and Carrier at its option, shall have the right to immediately seek redress through the Utah Courts in accordance with the terms and conditions of this Agreement, and the funds from any such check or other instrument shall be deemed to be held in trust for Carrier's benefit. It is further understood and agreed that should Customer send payment to Carrier, but the check, draft, money order, or other means of payment sent is payable to LA or jointly payable to LA and Carrier then, in such event, by execution of this Agreement, LA hereby appoints Carrier (and/or Carrier's assignee) as LA's attorney-in-fact for the limited purpose of endorsing such check(s), draft(s), money order(s), or other means of payment and authorizes Carrier (and/or Carrier's assignee) to deposit any such payment(s) into Carrier's (or Carrier's assignee's) bank account. Should Carrier's assignee require a separate document from LA requiring that LA appoint Carrier's assignee as LA's Attorney-in-Fact for the limited purpose of endorsing check(s), draft(s), money order(s), or other means of payment which will authorize Carrier's assignee to deposit any such payments into Carrier's assignee account, LA will timely execute such document. LA agrees that presentation of this Agreement to a Customer shall be sufficient documentation to authorize the Customer to pay Carrier in the event of any conflict.</li>
			<li>Right of Carrier to Decline Load. Carrier shall have the right to decline or refuse to do business for any reason with any Customer solicited by LA. LA understands and agrees that prior to accepting a load from a Customer, LA has the obligation to investigate the creditworthiness of said Customer on behalf of the Carrier. Carrier has the right to recover from LA, through payment, charge back, offset against other monies owing to LA, or otherwise, the amount of any amount not paid for by the Customer solicited by LA where the contract was timely and fully performed by the carrier ( "Bad Debt") within sixty (60) days, the amount of any collection and attorney fees (if any), and any advance on commission paid to LA in connection with such Bad Debt. The term "Bad Debt" does not include any load upon which there is any discount to the rate for any reason as determined by the customer. In such event, Carrier, not LA, is liable for the discounted rate. LA further agrees to cooperate with Carrier and to take any action(s) reasonably requested by Carrier to assist it in collecting any past due freight charges from a Customer. In the event a Bad Debt is collected, either in part or in full, Carrier and LA shall share in the recovery after the payment of any collection costs and attorney's fees at the same percentage split as was originally charged to LA. LA further agrees to adhere to Carrier's requirements regarding any necessary papers or documentation concerning the shipment arranged to be hauled. In the event that due to time constraints a shipment moves prior to LA discovering that Customer (or billing party) has insufficient credit, LA has the authority to act on behalf of the Carrier to demand payment of all freight charges from the Customer (or billing party) prior to delivery. LA will assist in this collection as necessary.</li>
			<li>
				Solicitation of Customers Following Termination. In the event this Agreement is terminated for any reason, LA agrees not to solicit nor accept business from Carrier's Customers and the Customers of other LAs of Carrier for a period of twelve (12) months following the termination of this Agreement. For purposes of this Agreement, any new customers that begin to ship with Carrier and LA after thirty (30) days from the signing of this Agreement will be considered Carrier's customers. Upon termination, if LA violates the non-solicitation/noncompetition provisions of this paragraph Carrier shall be entitled to liquidated damages in an amount equal to fifteen(15%) percent of the gross revenue generated to the violating party by such Customer(s) for a period of eighteen (18) months following the termination of this Agreement.
				<p>
					In addition, LA recognizes that the payment of damages hereunder may not fully compensate Carrier for LA's breach of the non-solicitation/non-competition provisions hereof and that Carrier will likely suffer irreparable harm from such a breach. Accordingly, LA agrees that should it breach, violate, or threaten to breach or violate the nonsolicitation/non-competition provisions hereof, that Carrier will be entitled injunctive relief prohibiting LA's breach, violation or continued breach or violation without the need of Carrier having to post any bond in connection with such injunctive relief. LA further agrees it shall protect and keep confidential any and all non-public, confidential, or proprietary information of Carrier that might be provided to LA in connection with performing this Agreement or otherwise and that LA shall not disclose the same, without the prior written approval of Carrier.
				</p>
			</li>
			<li>
				LA Representations. LA represents that neither it, nor any of its managers, directors, officers, owners, agents or employees are currently bound by or subject to any agency agreement or DOD-compete agreement with any other Carrier or third party that would restrict LA's rights or abilities to fully perform under this Agreement. LA understands and acknowledges that Carrier relies upon LA's representation regarding the lack of prior agency or non-compete agreements in entering into the LA Agreement and that LA's representation in this regard is important and material to Carrier. LA further understands and agrees to fully indemnify Carrier for any litigation arising between LA, including its managers, directors, officers, owners, agents or employees, and any third party involving existing agency agreements or non-compete agreements, and that such indemnity will include all costs and fees, including attorneys' fees, associated with any such litigation.
				<p>
					LA further represents that neither it, nor any of its managers, directors, officers, owners, agents or employees have retained any property or intellectual property of any kind, including pricing lists or customer lists, taken from or belonging to any other agent, transportation service, or any competitor of LA or Carrier. LA further represents and agrees that it will not use any property or intellectual property of any kind belonging to or improperly taken from any third party as it performs under the Limited Agency Agreement. LA understands and acknowledges that Carrier relies upon LA's representations regarding its retainer and use of property or intellectual property belonging to any third party and that LA's representation in this regard is important and material to Carrier. LA further understands and agrees to fully indemnify Carrier for any litigation arising between LA, including its managers, directors, officers, owners, agents or employees, and any third party involving property allegedly taken or retained by LA and that such indemnity will include all costs and fees, including attorney fees, associated with any such litigation.
				</p>
			</li>
			<li>Duty of Good Faith and Fair Dealing. Carrier and LA shall work in good faith to uphold the good reputation of each other and shall not take any action that would disparage or otherwise damage the reputation of the other. LA will not accept freight from any transportation service provider, broker, or agent to be "double brokered" or "convenience interlined" under Carrier's authority except where Carrier has approved of such practice in writing in advance of acceptance of a load(s) with another transportation service provider who may be operating as a "Shipper's Agent" or internal logistics unit for a shipper. Both parties hereto agree that there may be unforeseen market conditions and changes in law that require this Agreement to be modified; and both parties agree to make changes to this Agreement as necessary by written Addendum.</li>
			<li>
				Term of Agreement. The term of this Agreement shall be for a period of one year, renewed annually, provided, however, that the same may be terminated without cause upon fourteen (14) days written notice from either party to the other at any time. If LA engages in any prohibited practices, then Carrier, at Carrier's option, can declare an Event of Default and terminate this Agreement immediately. All terms and conditions of this Agreement that require the performance of the parties hereto for past and current loads related to customer service and payment shall continue in full force and effect until they are completed. Neither immediate termination nor a 14-day Notice to Terminate shall provide relief to the parties or allow them to ignore their obligations to each other for loads up to the point of termination.
				<p>
					In the event that this agreement is terminated by the Driver without 14-day written notice, it will be considered a default of the agreement. Such default will result in a $2,000 Early Termination Fee to paid by Driver to LA within ten (10) days of default. Driver and LA further acknowledges that the sums to be paid pursuant to this Section (i) constitute agreed upon and liquidated damages only, and not a penalty; and (ii) represent a reasonable and good faith attempt by LA, Driver and Carrier to ascertain the minimum damages that would be suffered by LA in the event of the default or early termination of this Agreement.
				</p>
			</li>
			<li>Dispute Resolution. Should the parties dispute some issue or problem not addressed in this Agreement, the parties hereto agree to attempt to resolve the issue or problem among themselves. If resolution is not achieved, then the parties agree to participate in non-binding mediation to resolve the issue or problem prior to implementing the Remedy in Paragraph 11.</li>
			<li>Enforcement. Should either party engage legal counsel to enforce any of the terms of this Agreement or to obtain any remedy or relief that might not otherwise be available in connection with this Agreement, then in such case, such party, if successful, shall be entitled to recover from the other party its reasonable costs and attorney fees incurred in taking such action.</li>
			<li>Processing Claims. LA agrees to process any and all claims on Carrier's behalf. In the event of a loss that cannot be offset by the Carrier (such as an act of God) that eliminates all or a part of the gross profit margin in the load, LA will pay back to Carrier the difference between what advance or commission LA was paid for the load at the same Commission Rate split less what the LA would be paid (if any) after adjusting for the claim on the load. Carrier and LA will share in any claims losses at the same commission rate</li>
			<li>Default and Event of Default. LA and Carrier will be in Default of this Agreement in the event either one of them fails to timely perform as to the sales, operational, or financial aspects contemplated by this Agreement. If the Driver gets off any truck for which LA is providing services without fourteen (14) day written notice provided to LA, he is in default of this agreement. If either party determines that the other party has breached this Agreement, it may notify the other party in writing that it is in Default of this Agreement by specifying the part of the Agreement that the other party is in Default, providing a Notice of Default mailed to the address in this Agreement, and providing a five (5) day period to cure. If the Default is not cured within five days, the non-defaulting party can notify the defaulting party of its intent to terminate this Agreement. In the event that the agreement is terminated, for any reason, before the full duration of the term of this agreement, Driver will incur an Early Termination Fee of no less than $10,000. LA, Driver, and Carrier acknowledge that the sums to be paid pursuant to this Section (i) constitute agreed upon and liquidated damages only, and not a penalty; and (ii) represent a reasonable and good faith attempt by LA and the Driver and Carrier to ascertain the minimum damages that would be suffered by LA in the event of the default or early termination of this Agreement. Upon termination of this Agreement, both parties hereto will still have responsibilities and obligations to the other party for loads up to and prior to the termination date. Both parties hereto agree to fulfill those responsibilities in accordance with the terms and conditions of this Agreement. Failure of the non-performing party to complete obligations agreed to herein will allow the other party to seek redress against the non-performing party through the processes described in paragraphs 10 and 11 hereto.</li>
			<li>Entire Contract. The provisions contained in this Agreement (including all schedules and addendums) properly express and memorialize the complete understanding and agreement between the parties, including those contained in all prior agreements, both verbal or written, and there are no other agreements or understanding between the parties, express or implied, except as set forth herein.</li>
			<li>Amendments. This Agreement may not be modified or amended except by a subsequent written amendment signed by both parties.</li>
			<li>Waivers. Waiver by either party of any failure to comply with any provision of this provision or a waiver of any other breach of or failure to comply with any other provision of this Agreement does not impair either party's rights to enforce the terms of this Agreement.</li>
			<li>Assignments. Neither party may assign its rights or obligations under this Agreement without the written consent of the other party.</li>
			<li>Binding Effect. This Agreement shall be binding upon the parties and their legal representatives successors and authorized assigns.</li>
			<li>Severability. If any provision of this Agreement is determined by a court of competent jurisdiction to be contrary to the laws or regulations of any applicable jurisdiction, then such invalid or unenforceable provision shall be severed from this Agreement; however, such determination shall not in any way affect the validity of any other provisions of this Agreement.</li>
			<li>Authority of Representatives to Bind Parties. It is agreed and warranted by the parties that the persons signing this Agreement respectively for Carrier and LA are authorized to do so. No further proof of authorizations is or shall be required. LA understands and agrees that it does not have the authority to sign on behalf of Carrier any documents except for those documents required for LA to perform its responsibilities spelled out in sections 1(A) through 1(I), above. LA specifically understands that it does NOT have the right to bind Carrier for credit, loans, sign checks, lease office space, lease vehicles, subscribe to telephone service, or any similar transactions. If LA exceeds the limitations of this paragraph, it shall be an Event of Default.</li>
			<li>Counterparts. This Agreement may be executed in any number of identical counterparts and each such executed counterpart shall be deemed a duplicate original hereof.</li>
			<li>Notices. Any notices required or permitted to be given under this Agreement shall be in writing and shall be sent by certified or registered mail, return receipt requested, and by fax transmission. The mailed notices shall be addressed to the parties, respectively, at the address shown below, and the contemporaneously faxed notices shall be likewise transmitted to the facsimile numbers shown below. Any Notice period referenced herein shall begin upon the third day from the postmark of the Notice sent by certified or registered mail.</li>
			<li>Background Check. Due to the nature of the freight business, LA agrees that by signing this Agreement that Carrier may at its option conduct a background check of LA and/or its principals, and LA will provide all necessary information for Carrier to accomplish this. In the event a background check discovers information that may create legal, moral, or liability issues for Carrier, Carrier reserves the right to terminate this Agreement immediately at its sole discretion.</li>
			<li>Governing Law. This Agreement shall be deemed to have been negotiated and entered into within the State of Utah. The laws of the State of Utah shall apply in interpreting and enforcing the terms of this Agreement. Each party hereto expressly submits to the jurisdiction of the state and federal courts of the State of Utah and Salt Lake County and agrees that venue in such Courts shall be proper and hereby waives any claims or defenses alleging that jurisdiction and/or venue in such Courts are improper or inconvenient.</li>
		</ol>
		<p>EXECUTED THIS <?=date('jS',strtotime($date))?> DAY OF <?=date('F',strtotime($date))?>, <?=date('Y',strtotime($date))?>.</p>
		<p><?=$fullname?> (DRIVER)</p>
		<p>By_______________________</p>
		<p>EXECUTED THIS <?=date('jS',strtotime($date))?> DAY OF <?=date('F',strtotime($date))?>, <?=date('Y',strtotime($date))?>.</p>
		<p>Arrowhead Dispatch Services LLC (LA)</p>
		<p>By</p>
		<p>Manager</p>
	</div>
	<p style="page-break-before: always">
</body>
</html>


